### ISSUE TITLE
Problem with the uninstall command of the Makefile

### ISSUE THREAD

**Issue by slashformotion** [z3oxs/ghost#5]
# what did I do ? 

i use  `make install-linux` 

Then i tried to uninstall ghost using the "uninstall" make command you provided and it did not work.
https://github.com/z3oxs/ghost/blob/2b446e7578577fa17675893d522e01b6846d14a0/Makefile#L5

# what happened

In my case the GOPATH is set to `~/CODE/GO/` so the binaries is here: `~/CODE/GO/bin/ghost`

If **GOPATH** is set to something other than `~/go/`, the binaries will not be in `~/go/bin/`. Your command will fail in that case.

**Comment by imf4ll** [comment]
I will try to fix that creating a dynamic workaround. To uninstall, you can simply go to your binaries location and remove ghost, its only a single binary
